In [2]:
import argparse
import time
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from scipy import sparse
from tqdm import tqdm
import ast

In [9]:
m = nn.Linear(4, 2)
opt = optim.Adam(m.parameters())
x = torch.rand((1,4))
y = torch.tensor([[0, 1]], dtype=torch.float32)
crit = torch.nn.BCEWithLogitsLoss()

out = m(x)
loss = crit(y, out)
loss.backward()

for i, param in enumerate(m.parameters()):
    if i == 0:
        print(param.grad)
        param.grad[range(2),range(2)] = torch.zeros_like(param.grad[range(2),range(2)])
        print('param')
        print(param.grad)

opt.step()
print('after optimizer step')
for param in m.parameters():
    print(param)

tensor([[-0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0759, -0.1042, -0.3527, -0.2138]])
param
tensor([[ 0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0759,  0.0000, -0.3527, -0.2138]])
after optimizer step
Parameter containing:
tensor([[ 0.4730, -0.2410, -0.2513,  0.2118],
        [ 0.2753,  0.2103,  0.2089,  0.2556]], requires_grad=True)
Parameter containing:
tensor([0.3012, 0.3216], requires_grad=True)
